export const GET_SPOTS = 'spots/getSpots'
export const GET_SPOT = 'spots/getSpot'
export const UPDATE_SPOT = 'spots/updateSpot'
export const DELETE_SPOT = 'spots/deleteSpot'
export const CREATE_SPOT = 'spots/createSpot'
export const ADD_IMAGE = 'spots/addImages'
export const ADD_REVIEW = 'spots/addReview'
export const GET_USER_SPOTS = 'spots/getUserSpots'